server:
  port: 8090
spring:
  redis:
    host: 67.209.185.193
    port: 6379
    jedis:
      pool:
        max-idle: 200
        min-idle: 0
        max-active: 1024
        max-wait: -1
    password: 123
    timeout: 10000